window.SLF=window.SLF||{};
(function(){
  let rootEl,rows=[],stopLive=null,filters={organization:'',department:'',search:''};
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const number=value=>new Intl.NumberFormat('th-TH',{maximumFractionDigits:2}).format(Number(value)||0);
  const money=value=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(Number(value)||0);
  const statusLabel={pending:'รอดำเนินการ',done:'นับแล้ว',review:'รอตรวจสอบ',missing:'ไม่พบสินค้า',locked:'ปิดยอดแล้ว'};
  async function render(root){rootEl=root;root.className='dashboard-page';root.innerHTML=skeleton();try{rows=await SLF.auth.dashboardData();draw();if(stopLive)stopLive();stopLive=SLF.auth.subscribeDashboard(async()=>{rows=await SLF.auth.dashboardData(true);draw();});}catch(error){root.innerHTML=`<div class="dash-error"><strong>ยังเปิด Dashboard ไม่ได้</strong><p>${esc(error.message)}</p><small>กรุณารันไฟล์ stock-count-dashboard.sql ใน Supabase</small></div>`;}}
  function skeleton(){return'<div class="dash-skeleton"><i></i><i></i><i></i><i></i></div>';}
  function unique(key){return[...new Map(rows.map(row=>[row[key],row])).values()];}
  function scoped(){const q=filters.search.toLocaleLowerCase('th-TH').trim();return rows.filter(row=>(!filters.organization||row.organization_id===filters.organization)&&(!filters.department||row.department_id===filters.department)&&(!q||`${row.item_code} ${row.item_name} ${row.counter_name} ${row.note}`.toLocaleLowerCase('th-TH').includes(q)));}
  function draw(){
    const data=scoped(),quantity=data.reduce((sum,row)=>sum+Number(row.total_quantity||0),0),value=data.reduce((sum,row)=>sum+Number(row.total_value||0),0),complete=data.filter(row=>['done','locked'].includes(row.status)).length,departments=new Set(data.map(row=>row.department_id)).size;
    rootEl.innerHTML=`<div class="dash-head"><div><h2>ภาพรวมการจัดทำ Stock Count</h2><p>ข้อมูลจะแสดงตามโรงพยาบาลและหน่วยงานที่บัญชีของคุณมีสิทธิ์เข้าถึงเท่านั้น</p></div><button class="btn" id="dashRefresh">↻ อัปเดตข้อมูล</button></div>
      <div class="dash-filters"><select id="dashOrg"><option value="">ทุกโรงพยาบาล</option>${unique('organization_id').map(row=>`<option value="${row.organization_id}" ${filters.organization===row.organization_id?'selected':''}>${esc(row.organization_name)}</option>`).join('')}</select><select id="dashDept"><option value="">ทุกหน่วยงาน</option>${unique('department_id').filter(row=>!filters.organization||row.organization_id===filters.organization).map(row=>`<option value="${row.department_id}" ${filters.department===row.department_id?'selected':''}>${esc(row.department_name)}</option>`).join('')}</select><input id="dashSearch" value="${esc(filters.search)}" placeholder="ค้นหา Item, ผู้ตรวจนับ หรือหมายเหตุ"></div>
      <section class="dash-stats"><article><span>รายการที่บันทึก</span><strong>${number(data.length)}</strong><small>สำเร็จ ${number(complete)} รายการ</small></article><article><span>หน่วยงาน</span><strong>${number(departments)}</strong><small>ตามขอบเขตสิทธิ์</small></article><article><span>จำนวนรวม</span><strong>${number(quantity)}</strong><small>หน่วยย่อยทั้งหมด</small></article><article class="value"><span>มูลค่ารวม</span><strong>${money(value)}</strong><small>คำนวณจากราคาต่อหน่วย</small></article></section>
      <section class="dash-card"><div class="dash-card-head"><div><h3>รายละเอียดการนับยอด</h3><p>${number(data.length)} รายการ · ${number(new Set(data.map(row=>row.organization_id)).size)} โรงพยาบาล</p></div><div class="dash-legend"><span class="done">นับแล้ว</span><span class="review">รอตรวจ</span><span class="missing">ไม่พบ</span></div></div><div class="dash-table-wrap"><table><thead><tr><th>รายการ</th><th>ผู้ตรวจนับ</th><th>สถานะ</th><th>LOT / EXP</th><th class="num">จำนวน</th><th class="num">มูลค่า</th><th>อัปเดต</th></tr></thead><tbody>${groupedDetailRows(data)||'<tr><td colspan="7" class="dash-empty">ยังไม่มีข้อมูลการนับในขอบเขตที่เลือก</td></tr>'}</tbody></table></div></section>`;
    bind();
  }
  function groupedDetailRows(data){const organizations=new Map();data.forEach(row=>{if(!organizations.has(row.organization_id))organizations.set(row.organization_id,{name:row.organization_name,rows:[]});organizations.get(row.organization_id).rows.push(row);});return[...organizations.values()].map(organization=>{const quantity=organization.rows.reduce((sum,row)=>sum+Number(row.total_quantity||0),0),value=organization.rows.reduce((sum,row)=>sum+Number(row.total_value||0),0),departments=new Map();organization.rows.forEach(row=>{if(!departments.has(row.department_id))departments.set(row.department_id,{name:row.department_name,rows:[]});departments.get(row.department_id).rows.push(row);});const departmentHtml=[...departments.values()].map(department=>{const departmentQuantity=department.rows.reduce((sum,row)=>sum+Number(row.total_quantity||0),0),departmentValue=department.rows.reduce((sum,row)=>sum+Number(row.total_value||0),0);return`<tr class="dash-dept-group"><td colspan="7"><div><span class="dash-dept-icon">D</span><strong>${esc(department.name)}</strong><small>${number(department.rows.length)} รายการ</small><span class="dash-dept-total">${number(departmentQuantity)} หน่วย · ${money(departmentValue)}</span></div></td></tr>${department.rows.map(detailRow).join('')}`;}).join('');return`<tr class="dash-org-group"><td colspan="7"><div><span class="dash-org-icon">H</span><strong>${esc(organization.name)}</strong><small>${number(departments.size)} หน่วยงาน · ${number(organization.rows.length)} รายการ</small><span class="dash-org-total">รวม ${number(quantity)} หน่วย · ${money(value)}</span></div></td></tr>${departmentHtml}`;}).join('');}
  function detailRow(row){const lots=Array.isArray(row.lots)?row.lots:[];return`<tr class="dash-detail-row"><td><strong>${esc(row.item_name)}</strong><small>${esc(row.item_code)} · ${esc(row.base_unit)}</small></td><td>${esc(row.counter_name||'-')}<small>${esc(row.note||'')}</small></td><td><span class="dash-status ${esc(row.status)}">${esc(statusLabel[row.status]||row.status)}</span></td><td><div class="dash-lots">${lots.slice(0,3).map(lot=>`<span>${esc(lot.lot||'ไม่ระบุ LOT')} · ${esc(lot.exp||'ไม่ระบุ EXP')}</span>`).join('')||'-'}${lots.length>3?`<small>+${lots.length-3} LOT</small>`:''}</div></td><td class="num"><strong>${number(row.total_quantity)}</strong><small>${esc(row.base_unit)}</small></td><td class="num"><strong>${money(row.total_value)}</strong></td><td>${row.updated_at?new Date(row.updated_at).toLocaleString('th-TH',{dateStyle:'short',timeStyle:'short'}):'-'}</td></tr>`;}
  function bind(){rootEl.querySelector('#dashRefresh').onclick=async()=>{rootEl.querySelector('#dashRefresh').disabled=true;rows=await SLF.auth.dashboardData(true);draw();};rootEl.querySelector('#dashOrg').onchange=e=>{filters.organization=e.target.value;filters.department='';draw();};rootEl.querySelector('#dashDept').onchange=e=>{filters.department=e.target.value;draw();};rootEl.querySelector('#dashSearch').oninput=e=>{filters.search=e.target.value;draw();const input=rootEl.querySelector('#dashSearch');input.focus();input.setSelectionRange(input.value.length,input.value.length);};}
  SLF.pages=SLF.pages||{};SLF.pages.dashboard={render};
})();
