window.SLF = window.SLF || {};

(function(){
  let rootEl,data=null,active='organizations',search='',stopLiveSync=null;
  const configs={
    organizations:{label:'โรงพยาบาล',fields:[['code','รหัสโรงพยาบาล','text'],['name','ชื่อโรงพยาบาล','text'],['is_active','เปิดใช้งาน','boolean']]},
    departments:{label:'หน่วยงาน',fields:[['organization_id','โรงพยาบาล','organization'],['code','รหัสหน่วยงาน','text'],['name','ชื่อหน่วยงาน','text'],['is_active','เปิดใช้งาน','boolean']]},
    items:{label:'Items',fields:[['organization_id','โรงพยาบาล','organization'],['item_id','item_id','text'],['code','item_code','text'],['name','item_name','text'],['base_unit','หน่วยย่อย','text'],['unit_price','ราคาต่อหน่วย','number'],['barcode','Barcode','text'],['category','หมวดหมู่','text'],['is_active','เปิดใช้งาน','boolean']]},
    packages:{label:'Packages',fields:[['item_id','Item','item'],['stock_item_unit_id','stock_item_unit_id','text'],['name','ชื่อ Package','text'],['size','ขนาดบรรจุ','number'],['barcode','Barcode','text']]},
    users:{label:'สิทธิ์ผู้ใช้',fields:[['organization_id','โรงพยาบาล','organization'],['department_id','หน่วยงาน','department'],['email','Email','email'],['role','Role','role']]}
  };
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function orgName(id){return data.organizations.find(x=>x.id===id)?.name||'-';}
  function deptName(id){return data.departments.find(x=>x.id===id)?.name||'-';}
  function itemName(id){const item=data.items.find(x=>x.id===id);return item?`${item.code} · ${item.name}`:'-';}
  function money(value){return new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',minimumFractionDigits:2}).format(Number(value)||0);}
  function rows(){return active==='users'?data.accessRules:data[active];}
  function displayValue(row,key){if(row.source==='platform_admin'&&key==='organization_id')return 'ทุกโรงพยาบาล';if(row.source==='platform_admin'&&key==='department_id')return 'ทุกหน่วยงาน';if(key==='organization_id')return orgName(row[key]);if(key==='department_id')return deptName(row[key]);if(active==='packages'&&key==='item_id')return itemName(row[key]);if(typeof row[key]==='boolean')return row[key]?'ใช่':'ไม่';return row[key]??'';}
  async function render(root){rootEl=root;root.className='sa-app';root.innerHTML='<div class="sa-loading">กำลังเปิดหน้าจัดการข้อมูล...</div>';try{if(!await SLF.auth.superAdminStatus()){root.innerHTML='<div class="sa-denied">บัญชีนี้ไม่มีสิทธิ์ Super Admin</div>';return;}await reload();if(stopLiveSync)stopLiveSync();stopLiveSync=SLF.auth.subscribeMasterData(()=>reload(true));}catch(error){root.innerHTML=`<div class="sa-denied">โหลดข้อมูลไม่สำเร็จ — ${esc(error.message)}</div>`;}}
  async function reload(force=false){data=await SLF.auth.superAdminData(force);draw();}
  function draw(){
    const cfg=configs[active],matches=rows().filter(row=>!search||JSON.stringify(row).toLowerCase().includes(search.toLowerCase())),filtered=matches.slice(0,200);
    rootEl.innerHTML=`<div class="sa-head"><div><h2>จัดการข้อมูลพื้นฐาน</h2><p>Super Admin · จัดการข้อมูลทุกโรงพยาบาล</p></div><div class="sa-head-actions"><button class="btn btn-primary" id="saImportBranch">⇧ นำเข้าตามสาขา</button><button class="btn btn-danger" id="saClearBranch">ล้างข้อมูลตามสาขา</button><button class="btn" id="saReload">↻ โหลดใหม่</button></div></div>
      <nav class="sa-tabs">${Object.entries(configs).map(([key,value])=>`<button class="btn ${active===key?'active':''}" data-tab="${key}">${value.label} <small>${key==='users'?data.accessRules.length:data[key].length}</small></button>`).join('')}</nav>
      <section class="sc-card sa-card"><div class="sa-toolbar"><input class="sa-search" id="saSearch" value="${esc(search)}" placeholder="ค้นหาใน ${esc(cfg.label)}"><span class="sa-result-hint">${matches.length>200?`แสดง 200 จาก ${matches.length} รายการ — ใช้ช่องค้นหาเพื่อกรอง`:''}</span><button class="btn btn-primary" id="saAdd">＋ เพิ่ม${esc(cfg.label)}</button></div>
      <div class="sa-table-wrap"><table class="data"><thead><tr>${cfg.fields.map(([,label])=>`<th>${esc(label)}</th>`).join('')}<th>จัดการ</th></tr></thead><tbody>${filtered.map(row=>`<tr class="${row.source==='platform_admin'?'sa-super-admin-row':''}">${cfg.fields.map(([key])=>`<td>${esc(displayValue(row,key))}</td>`).join('')}<td>${row.source==='platform_admin'?'<span class="sa-protected-role">Super Admin</span>':`<button class="btn btn-sm" data-edit="${row.id}">แก้ไข</button> <button class="btn btn-sm btn-danger" data-delete="${row.id}">ลบ</button>`}</td></tr>`).join('')||`<tr><td colspan="${cfg.fields.length+1}">ไม่พบข้อมูล</td></tr>`}</tbody></table></div></section>`;
    bind();
  }
  function bind(){
    rootEl.querySelector('#saReload').onclick=()=>reload(true);
    rootEl.querySelector('#saImportBranch').onclick=openBranchImport;
    rootEl.querySelector('#saClearBranch').onclick=openBranchClear;
    rootEl.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{active=button.dataset.tab;search='';draw();});
    rootEl.querySelector('#saSearch').oninput=e=>{search=e.target.value;draw();const input=rootEl.querySelector('#saSearch');input.focus();input.setSelectionRange(input.value.length,input.value.length);};
    rootEl.querySelector('#saAdd').onclick=()=>openForm(null);
    rootEl.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>openForm(rows().find(row=>row.id===button.dataset.edit)));
    rootEl.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>confirmDelete(button.dataset.delete));
  }
  function options(type,value){
    const source=type==='organization'?data.organizations:type==='department'?data.departments:data.items;
    return source.map(row=>`<option value="${row.id}" ${row.id===value?'selected':''}>${esc(type==='organization'?row.name:type==='department'?`${orgName(row.organization_id)} · ${row.name}`:`${orgName(row.organization_id)} · ${row.code} · ${row.name}`)}</option>`).join('');
  }
  function fieldHtml(field,row){const [key,label,type]=field,value=row?.[key];if(['organization','department','item'].includes(type))return `<label>${label}<select name="${key}" required><option value="">— เลือก —</option>${options(type,value)}</select></label>`;if(type==='boolean')return `<label>${label}<select name="${key}"><option value="true" ${value!==false?'selected':''}>เปิด</option><option value="false" ${value===false?'selected':''}>ปิด</option></select></label>`;if(type==='role'){const roles=[['admin','Admin'],['staff','Staff'],['user','User'],['super_admin','Super Admin']];return `<label>🛡️ ${label}<select name="${key}">${roles.map(([role,text])=>`<option value="${role}" ${value===role?'selected':''}>${text}</option>`).join('')}</select></label>`;}return `<label>${label}<input name="${key}" type="${type}" value="${esc(value??(type==='number'?0:''))}" ${['code','name','item_id','stock_item_unit_id','email'].includes(key)?'required':''}></label>`;}
  function openForm(row){
    const cfg=configs[active],modal=document.getElementById('modalRoot'),isUser=active==='users';
    const fields=isUser?`<div class="sa-user-scope">${cfg.fields.slice(0,2).map(field=>fieldHtml(field,row)).join('')}</div>${cfg.fields.slice(2).map(field=>fieldHtml(field,row)).join('')}`:cfg.fields.map(field=>fieldHtml(field,row)).join('');
    modal.innerHTML=`<div class="overlay"><div class="modal sc-import-preview-modal sa-editor-modal"><div class="sa-editor-head"><div class="sa-editor-icon">${isUser?'👤':'✏️'}</div><div><span>Master Data</span><h3>${row?'แก้ไข':'เพิ่ม'}${esc(cfg.label)}</h3><p>${isUser?'กำหนดบัญชีผู้ใช้และระดับสิทธิ์การเข้าถึง':'กรอกข้อมูลให้ครบถ้วนก่อนบันทึก'}</p></div></div>${row?`<div class="sa-edit-id"><span>ID</span><code title="${esc(row.id)}">${esc(row.id)}</code></div>`:''}<form id="saForm"><div class="sa-form">${fields}</div>${isUser?'<div class="sa-role-note" id="saRoleNote">🏥 สิทธิ์ทั่วไปต้องระบุโรงพยาบาลและหน่วยงาน</div>':''}<div id="saFormError" class="sa-error"></div><div class="row sa-editor-actions"><button type="button" class="btn" id="saCancel">ยกเลิก</button><button class="btn btn-primary">💾 บันทึก</button></div></form></div></div>`;
    if(isUser){
      const roleSelect=modal.querySelector('[name="role"]'),scope=modal.querySelector('.sa-user-scope'),note=modal.querySelector('#saRoleNote'),organizationSelect=modal.querySelector('[name="organization_id"]'),departmentSelect=modal.querySelector('[name="department_id"]');
      const syncDepartments=preserve=>{const selected=preserve?departmentSelect.value:'';departmentSelect.innerHTML=`<option value="">— เลือกหน่วยงาน —</option>${data.departments.filter(department=>department.organization_id===organizationSelect.value&&department.is_active!==false).map(department=>`<option value="${department.id}" ${department.id===selected?'selected':''}>${esc(department.name)}</option>`).join('')}`;departmentSelect.disabled=!organizationSelect.value;};
      organizationSelect.onchange=()=>syncDepartments(false);syncDepartments(true);
      const syncRole=()=>{const global=roleSelect.value==='super_admin';scope.hidden=global;organizationSelect.disabled=global;organizationSelect.required=!global;departmentSelect.disabled=global||!organizationSelect.value;departmentSelect.required=!global;note.classList.toggle('is-super',global);note.textContent=global?'🌐 Super Admin เข้าถึงและจัดการได้ทุกโรงพยาบาล โดยไม่ต้องเลือกหน่วยงาน':'🏥 สิทธิ์ทั่วไปต้องระบุโรงพยาบาลและหน่วยงาน';};
      roleSelect.onchange=syncRole;syncRole();
    }
    modal.querySelector('#saCancel').onclick=()=>modal.innerHTML='';modal.querySelector('#saForm').onsubmit=async e=>{e.preventDefault();const values={};cfg.fields.forEach(([key,,type])=>{let value=new FormData(e.target).get(key);if(type==='boolean')value=value==='true';if(type==='number')value=Number(value)||0;if(value==='')value=null;values[key]=value;});try{await SLF.auth.superAdminSave(active,row?.id,values);modal.innerHTML='';await reload();}catch(error){modal.querySelector('#saFormError').textContent=error.message;}};
  }
  function readWorkbook(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('ไม่สามารถอ่านไฟล์ได้'));reader.onload=e=>{try{resolve(XLSX.read(e.target.result,{type:'array'}));}catch(error){reject(error);}};reader.readAsArrayBuffer(file);});}
  function openBranchImport(){
    const modal=document.getElementById('modalRoot');
    const departmentOptions=organizationId=>data.departments.filter(row=>row.organization_id===organizationId&&row.is_active!==false).map(row=>`<option value="${row.id}">${esc(row.name)}</option>`).join('');
    modal.innerHTML=`<div class="overlay"><div class="modal sc-import-preview-modal sa-import-modal"><div class="sa-import-head"><div class="sa-import-icon">📥</div><div><span>นำเข้า Master Data</span><h3>นำเข้าข้อมูลตามสาขา</h3><p>ระบุพื้นที่ปลายทาง แล้วเลือกไฟล์ Template ที่ต้องการตรวจสอบ</p></div></div><div class="sa-template-download"><span class="sa-template-icon">📊</span><span><strong>ยังไม่มีไฟล์ Template?</strong><small>ดาวน์โหลดไฟล์ตัวอย่างพร้อมชื่อชีตและคอลัมน์ที่ถูกต้อง</small></span><button class="btn" id="saDownloadTemplate" type="button">⬇ ดาวน์โหลด Template</button></div><form id="saImportForm"><div class="sa-import-grid"><label><span>🏥 โรงพยาบาล/สาขา</span><select name="organization" required><option value="">— เลือกโรงพยาบาล —</option>${options('organization')}</select><small>เลือกโรงพยาบาลก่อนเพื่อแสดงหน่วยงาน</small></label><label><span>🏢 หน่วยงาน</span><select name="department" required disabled><option value="">— เลือกหน่วยงาน —</option></select><small id="saDepartmentHint">รอเลือกโรงพยาบาล</small></label></div><label class="sa-import-file"><input name="file" type="file" accept=".xlsx,.xls" required><span class="sa-import-file-icon">📄</span><span><strong>เลือกไฟล์ Template</strong><small>รองรับไฟล์ Excel .xlsx และ .xls</small></span><b>เลือกไฟล์</b></label><div id="saImportError" class="sa-error"></div><div class="row sa-import-actions"><button type="button" class="btn" id="saImportCancel">ยกเลิก</button><button class="btn btn-primary">🔍 ตรวจสอบข้อมูล</button></div></form></div></div>`;
    const organizationSelect=modal.querySelector('[name="organization"]'),departmentSelect=modal.querySelector('[name="department"]'),departmentHint=modal.querySelector('#saDepartmentHint');
    organizationSelect.onchange=()=>{
      const organization=data.organizations.find(row=>row.id===organizationSelect.value),available=organization?data.departments.filter(row=>row.organization_id===organization.id&&row.is_active!==false):[];
      departmentSelect.innerHTML=`<option value="">— เลือกหน่วยงาน —</option>${organization?departmentOptions(organization.id):''}`;
      departmentSelect.disabled=!organization||!available.length;
      departmentHint.textContent=!organization?'รอเลือกโรงพยาบาล':available.length?`พบ ${available.length} หน่วยงาน`:'โรงพยาบาลนี้ยังไม่มีหน่วยงาน';
    };
    const fileInput=modal.querySelector('[name="file"]'),fileTitle=modal.querySelector('.sa-import-file strong'),fileButton=modal.querySelector('.sa-import-file b');
    fileInput.onchange=()=>{fileTitle.textContent=fileInput.files[0]?.name||'เลือกไฟล์ Template';fileButton.textContent=fileInput.files.length?'เปลี่ยนไฟล์':'เลือกไฟล์';};
    modal.querySelector('#saDownloadTemplate').onclick=()=>SLF.pages.stockCount.downloadMasterTemplate();
    modal.querySelector('#saImportCancel').onclick=()=>modal.innerHTML='';
    modal.querySelector('#saImportForm').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target),organization=data.organizations.find(row=>row.id===form.get('organization')),department=data.departments.find(row=>row.id===form.get('department')),errorEl=modal.querySelector('#saImportError');if(!organization||!department||department.organization_id!==organization.id){errorEl.textContent='หน่วยงานไม่อยู่ในโรงพยาบาล/สาขาที่เลือก';return;}try{const workbook=await readWorkbook(form.get('file')),prepared=SLF.pages.stockCount.prepareMasterWorkbook(workbook,{organization,department});showBranchImportPreview(organization,department,prepared);}catch(error){errorEl.textContent=error.message;}};
  }
  function showBranchImportPreview(organization,department,prepared){
    const modal=document.getElementById('modalRoot'),packageCount=prepared.items.reduce((sum,item)=>sum+item.packages.length,0);
    modal.innerHTML=`<div class="overlay"><div class="modal sc-import-preview-modal"><h3>ยืนยันนำเข้าตามสาขา</h3><p><strong>${esc(organization.name)}</strong> · ${esc(department.name)}</p><div class="sc-preview-summary"><div><strong>${prepared.items.length}</strong><span>Items</span></div><div><strong>${packageCount}</strong><span>Packages</span></div><div><strong>${prepared.items.filter(item=>item.departmentLinked).length}</strong><span>รายการที่ผูก</span></div><div><strong>${prepared.payload.users.length}</strong><span>สิทธิ์ผู้ใช้</span></div></div>
      <h4 class="sa-preview-title">รายละเอียด Items และ Packages</h4><div class="sc-preview-table-wrap"><table class="data"><thead><tr><th>item_id</th><th>item_code</th><th>item_name</th><th>หน่วย</th><th>ราคา/หน่วย</th><th>Packages</th><th>ตำแหน่ง</th><th>ผูกหน่วยงาน</th></tr></thead><tbody>${prepared.items.map(item=>`<tr><td>${esc(item.itemId)}</td><td>${esc(item.code)}</td><td>${esc(item.name)}</td><td>${esc(item.baseUnit)}</td><td>${money(item.unitPrice)}</td><td>${esc(item.packages.map(pack=>`${pack.name} × ${pack.size}`).join(', '))}</td><td>${esc(item.location||'-')}</td><td>${item.departmentLinked?'ใช่':'ไม่'}</td></tr>`).join('')}</tbody></table></div>
      ${prepared.payload.users.length?`<h4 class="sa-preview-title">สิทธิ์ผู้ใช้ที่จะนำเข้า</h4><div class="sc-preview-table-wrap sa-user-preview"><table class="data"><thead><tr><th>Email</th><th>organization_code</th><th>department_code</th><th>Role</th></tr></thead><tbody>${prepared.payload.users.map(user=>`<tr><td>${esc(user.email)}</td><td>${esc(user.organizationcode||user.organization_code||organization.code)}</td><td>${esc(user.departmentcode||user.department_code||'')}</td><td>${esc(user.role||'user')}</td></tr>`).join('')}</tbody></table></div>`:''}
      <div class="sc-import-progress" id="saImportProgress" hidden><div><span>เตรียมนำเข้าข้อมูล</span><b>0%</b></div><div class="sc-import-progress-track"><i></i></div></div><div id="saImportError" class="sa-error"></div><div class="row"><button class="btn" id="saImportCancel">ยกเลิก</button><button class="btn btn-primary" id="saImportConfirm">ยืนยันนำเข้า</button></div></div></div>`;
    modal.querySelector('#saImportCancel').onclick=()=>modal.innerHTML='';modal.querySelector('#saImportConfirm').onclick=async()=>{const button=modal.querySelector('#saImportConfirm'),cancel=modal.querySelector('#saImportCancel'),progress=modal.querySelector('#saImportProgress'),errorEl=modal.querySelector('#saImportError');button.disabled=true;cancel.disabled=true;button.textContent='กำลังนำเข้า...';progress.hidden=false;progress.classList.remove('is-error');errorEl.textContent='';const updateProgress=({percent,label})=>{progress.querySelector('span').textContent=label;progress.querySelector('b').textContent=`${percent}%`;progress.querySelector('i').style.width=`${percent}%`;};try{await SLF.auth.importMasterData(organization.id,department.id,prepared.payload,updateProgress);await new Promise(resolve=>setTimeout(resolve,300));modal.innerHTML='';await reload();}catch(error){button.disabled=false;cancel.disabled=false;button.textContent='ลองนำเข้าอีกครั้ง';progress.classList.add('is-error');progress.querySelector('span').textContent='นำเข้าไม่สำเร็จ';errorEl.textContent=error.message;}};
  }
  function openBranchClear(){
    const modal=document.getElementById('modalRoot');modal.innerHTML=`<div class="overlay"><div class="modal"><h3>ล้างข้อมูลตามสาขา</h3><p>ลบ Items, Packages, การผูกหน่วยงาน และผลนับของโรงพยาบาลที่เลือก โดยไม่ลบโรงพยาบาล หน่วยงาน และผู้ใช้</p><form id="saClearForm"><div class="sa-form"><label>โรงพยาบาล/สาขา<select name="organization" required><option value="">— เลือก —</option>${options('organization')}</select></label></div><div id="saClearError" class="sa-error"></div><div class="row"><button type="button" class="btn" id="saClearCancel">ยกเลิก</button><button class="btn btn-danger">ยืนยันล้างข้อมูล</button></div></form></div></div>`;modal.querySelector('#saClearCancel').onclick=()=>modal.innerHTML='';modal.querySelector('#saClearForm').onsubmit=e=>{e.preventDefault();const organization=data.organizations.find(row=>row.id===new FormData(e.target).get('organization'));if(!organization)return;modal.innerHTML='';SLF.components.confirmModal('ยืนยันล้างข้อมูลสาขา',`ต้องการล้างข้อมูลสต็อกทั้งหมดของ <strong>${esc(organization.name)}</strong> ใช่หรือไม่?`,async()=>{try{await SLF.auth.clearOrganizationData(organization.id);await reload();}catch(error){SLF.components.alertModal('ล้างข้อมูลไม่สำเร็จ',error.message,'error');}},'ยืนยันล้างข้อมูล');};
  }
  function confirmDelete(id){const row=rows().find(value=>value.id===id),cfg=configs[active];SLF.components.confirmModal(`ลบ${cfg.label}`,`ยืนยันลบข้อมูลนี้ใช่หรือไม่? การลบอาจลบข้อมูลลูกที่เชื่อมโยงอยู่ด้วย`,async()=>{try{await SLF.auth.superAdminDelete(active,id);await reload();}catch(error){SLF.components.alertModal('ลบข้อมูลไม่สำเร็จ',error.message,'error');}},'ยืนยันลบ');}
  SLF.pages=SLF.pages||{};SLF.pages.superAdmin={render};
})();
