window.SLF = window.SLF || {};

(function(){
  let rootEl,data=null,active='organizations',search='',stopLiveSync=null;
  const configs={
    organizations:{label:'โรงพยาบาล',fields:[['code','รหัสโรงพยาบาล','text'],['name','ชื่อโรงพยาบาล','text'],['is_active','เปิดใช้งาน','boolean']]},
    departments:{label:'หน่วยงาน',fields:[['organization_id','โรงพยาบาล','organization'],['code','รหัสหน่วยงาน','text'],['name','ชื่อหน่วยงาน','text'],['is_active','เปิดใช้งาน','boolean']]},
    items:{label:'Items',fields:[['organization_id','โรงพยาบาล','organization'],['item_id','item_id','text'],['code','item_code','text'],['name','item_name','text'],['base_unit','หน่วยย่อย','text'],['unit_price','ราคาต่อหน่วย','number'],['barcode','Barcode','text'],['category','หมวดหมู่','text'],['is_active','เปิดใช้งาน','boolean']]},
    packages:{label:'Packages',fields:[['item_id','Item','item'],['stock_item_unit_id','stock_item_unit_id','text'],['name','ชื่อ Package','text'],['size','ขนาดบรรจุ','number'],['barcode','Barcode','text']]},
    users:{label:'สิทธิ์ผู้ใช้',fields:[['organization_id','โรงพยาบาล','organization'],['department_id','หน่วยงาน','department'],['email','Email','email'],['role','Role','role']]}
  };
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function orgName(id){return data.organizations.find(x=>x.id===id)?.name||'-';}
  function deptName(id){return data.departments.find(x=>x.id===id)?.name||'-';}
  function itemName(id){const item=data.items.find(x=>x.id===id);return item?`${item.code} · ${item.name}`:'-';}
  function money(value){return new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',minimumFractionDigits:2}).format(Number(value)||0);}
  function rows(){return active==='users'?data.accessRules:data[active];}
  function displayValue(row,key){if(row.source==='platform_admin'&&key==='organization_id')return 'ทุกโรงพยาบาล';if(row.source==='platform_admin'&&key==='department_id')return 'ทุกหน่วยงาน';if(key==='organization_id')return orgName(row[key]);if(key==='department_id')return deptName(row[key]);if(active==='packages'&&key==='item_id')return itemName(row[key]);if(typeof row[key]==='boolean')return row[key]?'ใช่':'ไม่';return row[key]??'';}
  async function render(root){rootEl=root;root.className='sa-app';root.innerHTML='<div class="sa-loading">กำลังเปิดหน้าจัดการข้อมูล...</div>';try{if(!await SLF.auth.superAdminStatus()){root.innerHTML='<div class="sa-denied">บัญชีนี้ไม่มีสิทธิ์ Super Admin</div>';return;}await reload();if(stopLiveSync)stopLiveSync();stopLiveSync=SLF.auth.subscribeMasterData(()=>reload(true));}catch(error){root.innerHTML=`<div class="sa-denied">โหลดข้อมูลไม่สำเร็จ — ${esc(error.message)}</div>`;}}
  async function reload(force=false){data=await SLF.auth.superAdminData(force);draw();}
  function draw(){
    const cfg=configs[active],matches=rows().filter(row=>!search||JSON.stringify(row).toLowerCase().includes(search.toLowerCase())),filtered=matches.slice(0,200);
    rootEl.innerHTML=`<div class="sa-head"><div><h2>จัดการข้อมูลพื้นฐาน</h2><p>Super Admin · จัดการข้อมูลทุกโรงพยาบาล</p></div><div class="sa-head-actions"><button class="btn btn-primary" id="saImportBranch">⇧ นำเข้าตามสาขา</button><button class="btn btn-danger" id="saClearBranch">ล้างข้อมูลตามสาขา</button><button class="btn" id="saReload">↻ โหลดใหม่</button></div></div>
      <nav class="sa-tabs">${Object.entries(configs).map(([key,value])=>`<button class="btn ${active===key?'active':''}" data-tab="${key}">${value.label} <small>${key==='users'?data.accessRules.length:data[key].length}</small></button>`).join('')}</nav>
      <section class="sc-card sa-card"><div class="sa-toolbar"><input class="sa-search" id="saSearch" value="${esc(search)}" placeholder="ค้นหาใน ${esc(cfg.label)}"><span class="sa-result-hint">${matches.length>200?`แสดง 200 จาก ${matches.length} รายการ — ใช้ช่องค้นหาเพื่อกรอง`:''}</span><button class="btn btn-primary" id="saAdd">＋ เพิ่ม${esc(cfg.label)}</button></div>
      <div class="sa-table-wrap"><table class="data"><thead><tr>${cfg.fields.map(([,label])=>`<th>${esc(label)}</th>`).join('')}<th>จัดการ</th></tr></thead><tbody>${filtered.map(row=>`<tr class="${row.source==='platform_admin'?'sa-super-admin-row':''}">${cfg.fields.map(([key])=>`<td>${esc(displayValue(row,key))}</td>`).join('')}<td>${row.source==='platform_admin'?'<span class="sa-protected-role">Super Admin</span>':`<button class="btn btn-sm" data-edit="${row.id}">แก้ไข</button> <button class="btn btn-sm btn-danger" data-delete="${row.id}">ลบ</button>`}</td></tr>`).join('')||`<tr><td colspan="${cfg.fields.length+1}">ไม่พบข้อมูล</td></tr>`}</tbody></table></div></section>`;
    bind();
  }
  function bind(){
    rootEl.querySelector('#saReload').onclick=()=>reload(true);
    rootEl.querySelector('#saImportBranch').onclick=openBranchImport;
    rootEl.querySelector('#saClearBranch').onclick=openBranchClear;
    rootEl.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{active=button.dataset.tab;search='';draw();});
    rootEl.querySelector('#saSearch').oninput=e=>{search=e.target.value;draw();const input=rootEl.querySelector('#saSearch');input.focus();input.setSelectionRange(input.value.length,input.value.length);};
    rootEl.querySelector('#saAdd').onclick=()=>openForm(null);
    rootEl.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>openForm(rows().find(row=>row.id===button.dataset.edit)));
    rootEl.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>confirmDelete(button.dataset.delete));
  }
  function options(type,value){
    const source=type==='organization'?data.organizations:type==='department'?data.departments:data.items;
    return source.map(row=>`<option value="${row.id}" ${row.id===value?'selected':''}>${esc(type==='organization'?row.name:type==='department'?`${orgName(row.organization_id)} · ${row.name}`:`${orgName(row.organization_id)} · ${row.code} · ${row.name}`)}</option>`).join('');
  }
  function fieldHtml(field,row){const [key,label,type]=field,value=row?.[key];if(['organization','department','item'].includes(type))return `<label>${label}<select name="${key}" required><option value="">— เลือก —</option>${options(type,value)}</select></label>`;if(type==='boolean')return `<label>${label}<select name="${key}"><option value="true" ${value!==false?'selected':''}>เปิด</option><option value="false" ${value===false?'selected':''}>ปิด</option></select></label>`;if(type==='role')return `<label>${label}<select name="${key}">${['admin','staff','user'].map(role=>`<option ${value===role?'selected':''}>${role}</option>`).join('')}</select></label>`;return `<label>${label}<input name="${key}" type="${type}" value="${esc(value??(type==='number'?0:''))}" ${['code','name','item_id','email'].includes(key)?'required':''}></label>`;}
  function openForm(row){const cfg=configs[active],modal=document.getElementById('modalRoot');modal.innerHTML=`<div class="overlay"><div class="modal sc-import-preview-modal"><h3>${row?'แก้ไข':'เพิ่ม'}${esc(cfg.label)}</h3>${row?`<div class="sa-edit-id"><span>ID</span><code title="${esc(row.id)}">${esc(row.id)}</code></div>`:''}<form id="saForm"><div class="sa-form">${cfg.fields.map(field=>fieldHtml(field,row)).join('')}</div><div id="saFormError" class="sa-error"></div><div class="row"><button type="button" class="btn" id="saCancel">ยกเลิก</button><button class="btn btn-primary">บันทึก</button></div></form></div></div>`;modal.querySelector('#saCancel').onclick=()=>modal.innerHTML='';modal.querySelector('#saForm').onsubmit=async e=>{e.preventDefault();const values={};cfg.fields.forEach(([key,,type])=>{let value=new FormData(e.target).get(key);if(type==='boolean')value=value==='true';if(type==='number')value=Number(value)||0;if(value==='')value=null;values[key]=value;});try{await SLF.auth.superAdminSave(active,row?.id,values);modal.innerHTML='';await reload();}catch(error){modal.querySelector('#saFormError').textContent=error.message;}};}
  function readWorkbook(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('ไม่สามารถอ่านไฟล์ได้'));reader.onload=e=>{try{resolve(XLSX.read(e.target.result,{type:'array'}));}catch(error){reject(error);}};reader.readAsArrayBuffer(file);});}
  function openBranchImport(){
    const modal=document.getElementById('modalRoot');
    modal.innerHTML=`<div class="overlay"><div class="modal sc-import-preview-modal"><h3>นำเข้าข้อมูลตามสาขา</h3><p>เลือกโรงพยาบาลและหน่วยงานปลายทางก่อนเลือกไฟล์ Template</p><form id="saImportForm"><div class="sa-form"><label>โรงพยาบาล/สาขา<select name="organization" required><option value="">— เลือก —</option>${options('organization')}</select></label><label>หน่วยงาน<select name="department" required><option value="">— เลือก —</option>${options('department')}</select></label><label>ไฟล์ Template<input name="file" type="file" accept=".xlsx,.xls" required></label></div><div id="saImportError" class="sa-error"></div><div class="row"><button type="button" class="btn" id="saImportCancel">ยกเลิก</button><button class="btn btn-primary">ตรวจสอบข้อมูล</button></div></form></div></div>`;
    modal.querySelector('#saImportCancel').onclick=()=>modal.innerHTML='';
    modal.querySelector('#saImportForm').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target),organization=data.organizations.find(row=>row.id===form.get('organization')),department=data.departments.find(row=>row.id===form.get('department')),errorEl=modal.querySelector('#saImportError');if(!organization||!department||department.organization_id!==organization.id){errorEl.textContent='หน่วยงานไม่อยู่ในโรงพยาบาล/สาขาที่เลือก';return;}try{const workbook=await readWorkbook(form.get('file')),prepared=SLF.pages.stockCount.prepareMasterWorkbook(workbook,{organization,department});showBranchImportPreview(organization,department,prepared);}catch(error){errorEl.textContent=error.message;}};
  }
  function showBranchImportPreview(organization,department,prepared){
    const modal=document.getElementById('modalRoot'),packageCount=prepared.items.reduce((sum,item)=>sum+item.packages.length,0);
    modal.innerHTML=`<div class="overlay"><div class="modal sc-import-preview-modal"><h3>ยืนยันนำเข้าตามสาขา</h3><p><strong>${esc(organization.name)}</strong> · ${esc(department.name)}</p><div class="sc-preview-summary"><div><strong>${prepared.items.length}</strong><span>Items</span></div><div><strong>${packageCount}</strong><span>Packages</span></div><div><strong>${prepared.items.filter(item=>item.departmentLinked).length}</strong><span>รายการที่ผูก</span></div><div><strong>${prepared.payload.users.length}</strong><span>สิทธิ์ผู้ใช้</span></div></div>
      <h4 class="sa-preview-title">รายละเอียด Items และ Packages</h4><div class="sc-preview-table-wrap"><table class="data"><thead><tr><th>item_id</th><th>item_code</th><th>item_name</th><th>หน่วย</th><th>ราคา/หน่วย</th><th>Packages</th><th>ตำแหน่ง</th><th>ผูกหน่วยงาน</th></tr></thead><tbody>${prepared.items.map(item=>`<tr><td>${esc(item.itemId)}</td><td>${esc(item.code)}</td><td>${esc(item.name)}</td><td>${esc(item.baseUnit)}</td><td>${money(item.unitPrice)}</td><td>${esc(item.packages.map(pack=>`${pack.name} × ${pack.size}`).join(', '))}</td><td>${esc(item.location||'-')}</td><td>${item.departmentLinked?'ใช่':'ไม่'}</td></tr>`).join('')}</tbody></table></div>
      ${prepared.payload.users.length?`<h4 class="sa-preview-title">สิทธิ์ผู้ใช้ที่จะนำเข้า</h4><div class="sc-preview-table-wrap sa-user-preview"><table class="data"><thead><tr><th>Email</th><th>organization_code</th><th>department_code</th><th>Role</th></tr></thead><tbody>${prepared.payload.users.map(user=>`<tr><td>${esc(user.email)}</td><td>${esc(user.organizationcode||user.organization_code||organization.code)}</td><td>${esc(user.departmentcode||user.department_code||'')}</td><td>${esc(user.role||'user')}</td></tr>`).join('')}</tbody></table></div>`:''}
      <div id="saImportError" class="sa-error"></div><div class="row"><button class="btn" id="saImportCancel">ยกเลิก</button><button class="btn btn-primary" id="saImportConfirm">ยืนยันนำเข้า</button></div></div></div>`;
    modal.querySelector('#saImportCancel').onclick=()=>modal.innerHTML='';modal.querySelector('#saImportConfirm').onclick=async()=>{const button=modal.querySelector('#saImportConfirm');button.disabled=true;button.textContent='กำลังนำเข้า...';try{await SLF.auth.importMasterData(organization.id,department.id,prepared.payload);modal.innerHTML='';await reload();}catch(error){button.disabled=false;button.textContent='ยืนยันนำเข้า';modal.querySelector('#saImportError').textContent=error.message;}};
  }
  function openBranchClear(){
    const modal=document.getElementById('modalRoot');modal.innerHTML=`<div class="overlay"><div class="modal"><h3>ล้างข้อมูลตามสาขา</h3><p>ลบ Items, Packages, การผูกหน่วยงาน และผลนับของโรงพยาบาลที่เลือก โดยไม่ลบโรงพยาบาล หน่วยงาน และผู้ใช้</p><form id="saClearForm"><div class="sa-form"><label>โรงพยาบาล/สาขา<select name="organization" required><option value="">— เลือก —</option>${options('organization')}</select></label></div><div id="saClearError" class="sa-error"></div><div class="row"><button type="button" class="btn" id="saClearCancel">ยกเลิก</button><button class="btn btn-danger">ยืนยันล้างข้อมูล</button></div></form></div></div>`;modal.querySelector('#saClearCancel').onclick=()=>modal.innerHTML='';modal.querySelector('#saClearForm').onsubmit=e=>{e.preventDefault();const organization=data.organizations.find(row=>row.id===new FormData(e.target).get('organization'));if(!organization)return;modal.innerHTML='';SLF.components.confirmModal('ยืนยันล้างข้อมูลสาขา',`ต้องการล้างข้อมูลสต็อกทั้งหมดของ <strong>${esc(organization.name)}</strong> ใช่หรือไม่?`,async()=>{try{await SLF.auth.clearOrganizationData(organization.id);await reload();}catch(error){alert(`ล้างข้อมูลไม่สำเร็จ: ${error.message}`);}},'ยืนยันล้างข้อมูล');};
  }
  function confirmDelete(id){const row=rows().find(value=>value.id===id),cfg=configs[active];SLF.components.confirmModal(`ลบ${cfg.label}`,`ยืนยันลบข้อมูลนี้ใช่หรือไม่? การลบอาจลบข้อมูลลูกที่เชื่อมโยงอยู่ด้วย`,async()=>{try{await SLF.auth.superAdminDelete(active,id);await reload();}catch(error){alert(`ลบไม่สำเร็จ: ${error.message}`);}},'ยืนยันลบ');}
  SLF.pages=SLF.pages||{};SLF.pages.superAdmin={render};
})();
